### PR TITLE
iPad 5 and iPad 6 support

### PR DESCRIPTION
**Pull request by iSapozhnik**

### CODE REVIEW

**Review by codytwinton — APPROVED** [review]
lgtm

**Review by codytwinton — CHANGES_REQUESTED** [review]
This looks great, but can you add this to the test cases?

**Comment by iSapozhnik** [comment]
@codytwinton sure! Will do.

**Comment by iSapozhnik** [comment]
@codytwinton Done!

**Review by codytwinton — APPROVED** [review]
noice

**Pull request merged**
