### PR TITLE
Support Swift 3.0

### PR DESCRIPTION
**Pull request by zhouhao27**
- Support Swift 3.0 in Xcode 8 beta 6.

### CODE REVIEW

**Comment by schickling** [comment]
Thanks 👍

**Comment by Tokuriku** [comment]
This breaks if under Swift 3.0..

**Comment by schickling** [comment]
@zhouhao27 any ideas?

Should I revert this @Tokuriku?

**Comment by zhouhao27** [comment]
@Tokuriku I'll check that. But what is your problem? I have no problem to build it in Swift 3.0

**Comment by zhouhao27** [comment]
@schickling I found when we use the `pod install`, it still get the old source code. Should we update the CocoaPods in some way?

If I use the following Podfile, it will be ok.

```
platform :ios, '8.0'
use_frameworks!

target ‘DeviceDemo’ do
  pod 'Device.swift', :git => 'https://github.com/schickling/Device.swift'
end
```

**Comment by schickling** [comment]
LGTM. Does that work for you @Tokuriku?

**Comment by Tokuriku** [comment]
@schickling No, there is no need to revert this.

For my projects, I need the changes in commit: a72f60f0ef65d11f74deb981fb683d96ef27eaff
Otherwise, the plist is copied in the app bundle and the app gets refused by Apple.

The best solution for me would be If you could do a cocoapods release at or a bit above that commit otherwise I'm stuck using your master branch.

As an aside, I would highly recommend you create a [swift 3] branch until it gets out of beta ;)

**Pull request merged**
