### PR TITLE
readme fix

### PR DESCRIPTION
**Pull request by efremidze**
You have to use Device.swift for now. Changing the name of the repo to `Device` might be a good idea.

### CODE REVIEW

**Comment by schickling** [comment]
Unfortunately [someone else](https://github.com/Ekhoo/Device) just took this name :horse:

**Comment by schickling** [comment]
@Ekhoo any plans to merge? :)

**Comment by Ekhoo** [comment]
@schickling what do you want to merge ?

**Comment by schickling** [comment]
I was just thinking since you just also created a package named like this one if you'd be interested in merge it into this one.

**Comment by Ekhoo** [comment]
Thank you for your proposal, but I prefer to stay free :)

**Comment by schickling** [comment]
Sure thing :)

**Pull request closed without merging**
