### PR TITLE
Updated Readme & String enum for Devices

### PR DESCRIPTION
**Pull request by Hendrik44**
Updated pull request for current version

### CODE REVIEW

**Comment by schickling** [comment]
I'll merge this. Hopefully this doesn't break anything for people :)

**Comment by Hendrik44** [comment]
The the String values can be used optional (raw-Value) to get device String, so it shouldn't be problematic ;-)

**Comment by kudit** [comment]
Is there a reason you define the raw value as a string vs just using the Swift string conversion on the variable name (since it appears your strings are identical anyways)? Seems like this is ripe for typos and unnecessary additional maintenance. 

http://stackoverflow.com/a/31893968/897883

**Comment by Hendrik44** [comment]
I want use the device names for App-Tracking. Seem you are right and i can use the string conversion, so the raw-values could be removed. Should i remove it and make a pull-reguest?

**Comment by schickling** [comment]
I'd be happy to merge it in, can't provide too much feedback though, since I'm currently not using this package any more.

**Pull request merged**
