### PR TITLE
Add iPhone8, iPhone8Plus, iPhoneX

### PR DESCRIPTION
**Pull request by mlight3**
- Add iPhone8, iPhone8Plus, iPhoneX
- Change order of iPhoneSE

### CODE REVIEW

**Comment by igorkislyuk** [comment]
Let's wait few days until official release of Xcode 9 / iOS 11

**Comment by RyanRamchandar** [comment]
Xcode 9 / iOS 11 is out now, and this LGTM

**Comment by igorkislyuk** [comment]
I know. Will test and merge in this weekends

**Comment by RyanRamchandar** [comment]
@mlight3 If you get the chance please also update the tests with these new devices.

@igorkislyuk thanks.

**Comment by igorkislyuk** [comment]
@mlight3 Pull request is good, otherwise few changes are required:

- add tests
- bump version to `1.0`
- update [changelog.md](https://github.com/schickling/Device.swift/blob/master/CHANGELOG.md)

After you are finish, just mention me. I'll check and we are done in this PR. :)

P. S. Nvm done it myself.

**Comment by mlight3** [comment]
@igorkislyuk Great! and Thanks! 👍

**Pull request merged**
