### PR TITLE
Added recent iPad devices

### PR DESCRIPTION
**Pull request by maxchuquimia**
Added some recent iPad identifier :)

### CODE REVIEW

**Comment by igorkislyuk** [comment]
Will test and update library this weekend. Thank you.

**Comment by codytwinton** [comment]
@igorkislyuk Thanks for handling the testing. Looks good @Jugale

**Comment by igorkislyuk** [comment]
Tests are passed. Very good pool request. Thank you, @Jugale :)

**Comment by igorkislyuk** [comment]
Version 1.1 is available now

**Pull request merged**
